# Generated by Django 5.2.12 on 2026-03-12 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=150)),
                ('task_author', models.CharField(blank=True, max_length=100)),
                ('task_description', models.TextField(blank=True)),
                ('task_status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Terminada')], default='pending', max_length=20)),
                ('task_due_date', models.DateTimeField(blank=True, null=True)),
                ('task_created_at', models.DateTimeField(auto_now_add=True)),
                ('task_modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-task_created_at'],
            },
        ),
    ]
